### ISSUE TITLE
SSU database?

### ISSUE THREAD

**Issue by Anto007** [bengtssonpalme/MetaxaQR#1]
I'm yet to test out MetaxaQR but could you clarify which SSU database is going to be installed via `metaxaQR_install_database -g SSU` Is it going to be a hand-curated version of the SILVA v138.1? Thank you.

**Comment by bengtssonpalme** [comment]
That will be the new semi-hand curated database, produced with the new version of the MetaxaQR database builder. It is impossible to hand curate the entire SILVA database these days.

**Comment by Anto007** [comment]
Thanks but may I know the original source of this semi-hand-curated database? Is it for example based on SILVA or GenBank or GTDB?

**Comment by bengtssonpalme** [comment]
It's SILVA 138. If you type just `metaxaQR_install_database` at the terminal, you will get this information. (Well it actually says it is hand curated, which we should change as that is only partially true...)

**Comment by Anto007** [comment]
Thanks again; Sorry, I should have gone ahead and tested your tool and my query would have been answered. Looking forward to doing it very soon.
